// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheVideoGameStore.Inventory.Infastructure;

#nullable disable

namespace TheVideoGameStore.Inventory.Infastructure.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20211207150915_AddedStock")]
    partial class AddedStock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("platform", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XboxOne"
                        },
                        new
                        {
                            Id = 2,
                            Name = "XboxSeriesX"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Playstation4"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Playstation5"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NintendoSwitch"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("productType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Console"
                        },
                        new
                        {
                            Id = 2,
                            Name = "VideoGame"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessory"
                        });
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.StockItemAggregate.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("condition", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Preowned"
                        });
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.StockItemAggregate.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("ProductId");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.Product", b =>
                {
                    b.HasOne("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.StockItemAggregate.Stock", b =>
                {
                    b.HasOne("TheVideoGameStore.Inventory.Domain.AggregatesModel.StockItemAggregate.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.Product", "Product")
                        .WithMany("Stock")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TheVideoGameStore.Inventory.Domain.AggregatesModel.ProductAggregate.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
