name: Build Inventory

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Inventory.sln
    - name: Build
      run: dotnet build src/Inventory.sln --no-restore -c Release
    - name: Test
      run: dotnet test src/Inventory.sln --no-build -c Release --verbosity normal
