name: Release Inventory

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        source-url: https://pkgs.dev.azure.com/ianmutch0535/_packaging/ianmutch0535/nuget/v3/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.ADO_NUGET_AUTH}}
        
    # If automated release
    - if: github.event_name == 'release'
      name: Set release environment version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    # Else if triggered manually
    - if: github.event_name == 'workflow_dispatch'
      name: Set manual environment version
      run: echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

    # Build with implicit restore
    - name: Build
      run: dotnet build src/Inventory.sln -c Release -p:Version=${{ env.RELEASE_VERSION }}
      
    - name: Test
      run: dotnet test src/Inventory.sln --no-build -c Release --verbosity normal

    - name: Publish Nuget to Azure Artifacts
      run: dotnet nuget push src/Inventory.ApiClient/bin/Release/*.nupkg  --no-symbols --skip-duplicate
