name: Release Inventory

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    # If automated release
    - if: github.event_name == 'release'
      name: Set release environment version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    # Else if triggered manually
    - if: github.event_name == 'workflow_dispatch'
      name: Set manual environment version
      run: echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

    # Build with implicit restore
    - name: Build
      run: dotnet build src/Inventory.sln --no-restore -c Release -p:Version=${{ env.RELEASE_VERSION }}
      
    - name: Test
      run: dotnet test src/Inventory.sln --no-build -c Release --verbosity normal
      
    - name: Add Nuget Source
      run: dotnet nuget add source --username Ian-Mutch --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Ian-Mutch/index.json"

    - name: Push to GitHub Nuget Feed
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ }} --source "github"
